Stratis.FederatedSidechains.AdminDashboard/Controllers/SidechainNodeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Stratis.FederatedSidechains.AdminDashboard.Filters;
using Stratis.FederatedSidechains.AdminDashboard.Rest;
using Stratis.FederatedSidechains.AdminDashboard.Settings;

namespace Stratis.FederatedSidechains.AdminDashboard.Controllers
{
    [Route("sidechain-node")]
    public class SidechainNodeController : Controller
    {
        private readonly DefaultEndpointsSettings defaultEndpointsSettings;

        public SidechainNodeController(IOptions<DefaultEndpointsSettings> defaultEndpointsSettings)
        {
            this.defaultEndpointsSettings = defaultEndpointsSettings.Value;
        }

        [Ajax]
        [Route("enable-federation")]
        public async Task<IActionResult> EnableFederationAsync(string mnemonic, string password)
        {
            ApiResponse importWalletRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.SidechainNode, "/api/FederationWallet/import-key", new {mnemonic, password});
            if(importWalletRequest.IsSuccess)
            {
                ApiResponse enableFederationRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.SidechainNode, "/api/FederationWallet/enable-federation", new {password});
                return enableFederationRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
            }
            return BadRequest();
        }

        [Ajax]
        [HttpPost]
        [Route("resync")]
        public async Task<IActionResult> ResyncAsync(string value)
        {
            bool isHeight = int.TryParse(value, out int height);
            if(isHeight)
            {
                ApiResponse getblockhashRequest = await ApiRequester.GetRequestAsync(this.defaultEndpointsSettings.SidechainNode, $"/api/Consensus/getblockhash?height={value}");
                ApiResponse syncRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.SidechainNode, "/api/Wallet/sync", new {hash=((string)getblockhashRequest.Content)});
                return syncRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
            }
            else
            {
                ApiResponse syncRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.SidechainNode, "/api/Wallet/sync", new {hash=value});
                return syncRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
            }
        }

        [Ajax]
        [Route("resync-crosschain-transactions")]
        public async Task<IActionResult> ResyncCrosschainTransactionsAsync()
        {
            //TODO: implement this method
            ApiResponse stopNodeRequest = await ApiRequester.GetRequestAsync(this.defaultEndpointsSettings.StratisNode, "/api/Node/status");
            return stopNodeRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
        }

        [Ajax]
        [Route("stop")]
        public async Task<IActionResult> StopNodeAsync()
        {
            ApiResponse stopNodeRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.SidechainNode, "/api/Node/stop", true);
            return stopNodeRequest.IsSuccess ? (IActionResult)Ok() : BadRequest();
        }
    }
}

Stratis.FederatedSidechains.AdminDashboard/Controllers/StratisNodeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Stratis.FederatedSidechains.AdminDashboard.Filters;
using Stratis.FederatedSidechains.AdminDashboard.Rest;
using Stratis.FederatedSidechains.AdminDashboard.Settings;

namespace Stratis.FederatedSidechains.AdminDashboard.Controllers
{
    [Route("stratis-node")]
    public class StratisNodeController : Controller
    {
        private readonly DefaultEndpointsSettings defaultEndpointsSettings;

        public StratisNodeController(IOptions<DefaultEndpointsSettings> defaultEndpointsSettings)
        {
            this.defaultEndpointsSettings = defaultEndpointsSettings.Value;
        }

        [Ajax]
        [HttpPost]
        [Route("resync")]
        public async Task<IActionResult> ResyncAsync(string value)
        {   
            bool isHeight = int.TryParse(value, out int height);
            if(isHeight)
            {
                ApiResponse getblockhashRequest = await ApiRequester.GetRequestAsync(this.defaultEndpointsSettings.StratisNode, $"/api/Consensus/getblockhash?height={value}");
                ApiResponse syncRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.StratisNode, "/api/Wallet/sync", new {hash=((string)getblockhashRequest.Content)});
                return syncRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
            }
            else
            {
                ApiResponse syncRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.StratisNode, "/api/Wallet/sync", new {hash=value});
                return syncRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
            }
        }

        [Ajax]
        [Route("resync-crosschain-transactions")]
        public async Task<IActionResult> ResyncCrosschainTransactionsAsync()
        {
            //TODO: implement this method
            ApiResponse stopNodeRequest = await ApiRequester.GetRequestAsync(this.defaultEndpointsSettings.StratisNode, "/api/Node/status");
            return stopNodeRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
        }

        [Ajax]
        [Route("stop")]
        public async Task<IActionResult> StopNodeAsync()
        {
            ApiResponse stopNodeRequest = await ApiRequester.PostRequestAsync(this.defaultEndpointsSettings.StratisNode, "/api/Node/stop", true);
            return stopNodeRequest.IsSuccess ? (IActionResult) Ok() : BadRequest();
        }
    }
}

Stratis.FederatedSidechains.AdminDashboard/Views/Shared/Initialization.cshtml
<partial name="Loader" />

<!-- Modal Enable F. -->
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="enableF" tabindex="-1" role="dialog" aria-labelledby="enableF" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Enable Federation</h5>
            </div>
            <div class="modal-body">
                <p class="text-muted my-2 text-center">Some text explaining what this does</p>
                <form class="my-3" data-ajax="true" asp-controller="SidechainNode" asp-action="EnableFederationAsync" data-ajax-begin="BeginAction();" data-ajax-complete="CompleteAction();" data-ajax-success="HideModals();EnabledFederation();" data-ajax-failure="EnableFederationFailed">
                    <div class="form-group">
                        <label for="Mnemonics">Mnemonics</label>
                        <input type="text" class="form-control" autocomplete="off" name="mnemonic" id="Mnemonics" aria-describedby="Mnemonics" placeholder="Enter Mnemonics here">
                    </div>
                    <div class="form-group">
                        <label for="Password">Password</label>
                        <input type="password" class="form-control" autocomplete="off" name="password" id="Password" placeholder="Password here">
                    </div>
                    <button type="submit" class="btn btn-primary d-flex justify-content-end ml-auto">Enable Federation</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /Modal Enable F. -->

@if(ViewBag.NodeUnavailable)
{
    @section Scripts
    {
        <script type="text/javascript">
        $(document).ready(function()
        {
            Snackbar.show({text: "The full nodes API are unavailable", pos: "bottom-center", duration: 0, actionText: 'REFRESH', onActionClick: function(element) {document.location.reload();}});
            setTimeout(function() {
                document.location.reload();
            }, 10000);
        });
        </script>
    }
}
else
{
    @section Scripts
    {
        <script type="text/javascript">
        $(document).ready(function()
        {
            setTimeout(function() {
                document.location.reload();
            }, 3000);
        });
        </script>
    }
}

Stratis.FederatedSidechains.AdminDashboard/Views/Shared/Loader.cshtml
<div class="loader">
    <div class="atom-spinner">
        <div class="spinner-inner">
            <div class="spinner-line"></div>
            <div class="spinner-line"></div>
            <div class="spinner-line"></div>
            <div class="spinner-circle">
                &#9679;
            </div>
        </div>
    </div>
    <p>Initializing...</p>
</div>

Stratis.FederatedSidechains.AdminDashboard/Views/Shared/Modals.cshtml
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="stratisResyncCrosschain" tabindex="-1" role="dialog" aria-labelledby="resyncCrosschain" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Resync Crosschain transactions</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-muted my-2 text-center">Some text explaining what this does</p>
                <span class="d-flex justify-content-center my-4">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <a data-ajax="true" asp-controller="StratisNode" asp-action="ResyncCrosschainTransactionsAsync" data-ajax-begin="HideModals" data-ajax-success="StratisCrosschainResynced" data-ajax-failure="StratisCrosschainResyncFailed" class="btn btn-danger ml-3">Resync Crosschain Transactions</a>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="stratisResyncBlockchain" tabindex="-1" role="dialog" aria-labelledby="resyncBlockchain" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Resync Stratis Blockchain</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-muted my-2 text-center">Some text explaining what this does</p>
                <form class="my-3" data-ajax="true" asp-controller="StratisNode" asp-action="ResyncAsync" data-ajax-begin="HideModals" data-ajax-success="StratisResyncedBlockchain" data-ajax-failure="StratisResyncBlockchainFailed" method="post">
                    <div class="form-group">
                        <label for="value">Block height/Hash</label>
                        <input type="text" class="form-control" name="value" required id="value" aria-describedby="value" placeholder="Enter Block height or Block Hash here">
                    </div>
                    <span class="d-flex justify-content-center my-4">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary ml-3">Resync Blockchain</button>
                    </span>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="stratisStopNode" tabindex="-1" role="dialog" aria-labelledby="stopNode" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Stop Mainnet Node</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">Are you sure to stop the node ?</div>
                <span class="d-flex justify-content-center my-4">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <a data-ajax="true" asp-controller="StratisNode" asp-action="StopNodeAsync" data-ajax-begin="HideModals" data-ajax-success="StratisNodeStopped" data-ajax-failure="StratisNodeStopFailed" class="btn btn-danger ml-3">Stop the node</a>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="sidechainResyncCrosschain" tabindex="-1" role="dialog" aria-labelledby="resyncCrosschain" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="">Resync Crosschain transactions</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p class="text-muted my-2 text-center">Some text explaining what this does</p>
            <span class="d-flex justify-content-center my-4">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                <a data-ajax="true" asp-controller="SidechainNode" asp-action="ResyncCrosschainTransactionsAsync" data-ajax-begin="HideModals" data-ajax-success="SidechainCrosschainResynced" data-ajax-failure="SidechainCrosschainResyncFailed" class="btn btn-danger ml-3">Resync Crosschain Transactions</a>
            </span>
        </div>
    </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="sidechainResyncBlockchain" tabindex="-1" role="dialog" aria-labelledby="resyncBlockchain" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Resync Sidechain Blockchain</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-muted my-2 text-center">Some text explaining what this does</p>
                <form class="my-3" data-ajax="true" asp-controller="SidechainNode" asp-action="ResyncAsync" data-ajax-begin="HideModals" data-ajax-success="SidechainResyncedBlockchain" data-ajax-failure="SidechainResyncBlockchainFailed" method="post">
                    <div class="form-group">
                        <label for="value">Block height/Hash</label>
                        <input type="text" class="form-control" name="value" required id="value" aria-describedby="value" placeholder="Enter Block height or Block Hash here">
                    </div>
                    <span class="d-flex justify-content-center my-4">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary ml-3">Resync Blockchain</button>
                    </span>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="sidechainStopNode" tabindex="-1" role="dialog" aria-labelledby="stopNode" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Stop Mainnet Node</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info" role="alert">Are you sure to stop the node ?</div>
                <span class="d-flex justify-content-center my-4">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <a data-ajax="true" asp-controller="SidechainNode" asp-action="StopNodeAsync" data-ajax-begin="HideModals" data-ajax-success="SidechainNodeStopped" data-ajax-failure="SidechainNodeStopFailed" class="btn btn-danger ml-3">Stop the node</a>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="stratisHistory" tabindex="-1" role="dialog" aria-labelledby="stratisHistory" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">History</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-sm my-3">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">Status</th>
                            <th class="text-center" scope="col">Destination</th>
                            <th class="text-center" scope="col">Tx ID</th>
                            <th class="text-center" scope="col">Confirmed in block</th>
                            <th class="text-center" scope="col">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(dynamic transaction in (JArray)ViewBag.History[0])
                        {
                            <tr>
                                <td class="text-center"><i class="material-icons text-green md-18">check_circle</i></td>
                                <td class="text-center text-truncate"><code>@(transaction.withdrawal.targetAddress)</code></td>
                                <td class="text-left text-truncate" style="max-width: 110px;"><a href="https://chainz.cryptoid.info/strat/tx.dws?@(transaction.id).htm" target="_blank">@transaction.withdrawal.id</a></td>
                                <td class="text-center">@transaction.withdrawal.blockNumber</td>
                                <td class="text-right">@(((double)transaction.withdrawal.amount/100000000).ToString("N8")) @ViewBag.StratisTicker</td>
                            </tr>
                        }
                    </tbody>
                    @if(((JArray)ViewBag.History[0]).Count == 0)
                    {
                        <tfoot>
                            <tr>
                                <td colspan="6" class="text-center"><em>There no transaction to display.</em></td>
                            </tr>
                        </tfoot>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="sidechainHistory" tabindex="-1" role="dialog" aria-labelledby="sidechainHistory" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">History</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-sm my-3">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">Status</th>
                            <th class="text-center" scope="col">Destination</th>
                            <th class="text-center" scope="col">Tx ID</th>
                            <th class="text-center" scope="col">Confirmed in block</th>
                            <th class="text-center" scope="col">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(dynamic transaction in (JArray)ViewBag.History[1])
                        {
                            <tr>
                            <td class="text-center"><i class="material-icons text-green md-18">check_circle</i></td>
                            <td class="text-center text-truncate"><code>@(transaction.withdrawal.targetAddress)</code></td>
                            <td class="text-left text-truncate" style="max-width: 110px;"><a href="https://chainz.cryptoid.info/strat/tx.dws?@(transaction.id).htm" target="_blank">@transaction.withdrawal.id</a></td>
                            <td class="text-center">@transaction.withdrawal.blockNumber</td>
                            <td class="text-right">@(((double)transaction.withdrawal.amount/100000000).ToString("N8")) @ViewBag.SidechainTicker</td>
                            </tr>
                        }
                    </tbody>
                    @if(((JArray)ViewBag.History[1]).Count == 0)
                    {
                        <tfoot>
                            <tr>
                            <td colspan="6" class="text-center"><em>There no transaction to display.</em></td>
                            </tr>
                        </tfoot>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

Stratis.FederatedSidechains.AdminDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Stratis Federated Sidechains Dashboard</title>
    <environment include="Development">
      <link href="~/css/default.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
      <link href="~/css/default.min.css" rel="stylesheet" />
    </environment>
    <link rel="stylesheet" type="text/css" href="~/lib/node-snackbar/dist/snackbar.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/nprogress/nprogress.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/@@fortawesome/fontawesome-free/css/all.css" />
    <link rel="icon" type="image/svg" href="~/images/logo.svg" />
</head>
<body>
  <div class="modal fade" data-keyboard="false" data-backdrop="static" id="miningPublicKeys" tabindex="-1" role="dialog" aria-labelledby="miningPublicKeys" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="">Mining Public Keys</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-unstyled align-items-center flex-column d-flex">
            @foreach(var miningPubKey in (ViewBag.MiningPubKeys ?? (new string[] {})))
            {
              <li class="py-2">
                <code>@miningPubKey</code>
                <a href="#" class="text-primary ml-2 copy-clipboard">Copy</a>
              </li>
            }
          </ul>
          @if(ViewBag.MiningPubKeys == null)
          {
            <p class="text-center text-muted"><em>Missing Mining Public Keys</em></p>
          }
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary mx-auto" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-purple fixed-top">
    <a class="navbar-brand mr-4" href="https://stratisplatform.com/" target="_blank">
      <img src="~/images/logo_white.svg" width="30" height="30" class="d-inline-block align-top" alt="Stratis" />
    </a>
    <div class="navbar-text text-white">Federation members dashboard for Apex</div>
    <span class="badge badge-purple ml-auto">Status: <span class="status">@(ViewBag.Status ?? "Warning")</span></span>
  </nav>
  <nav class="navbar navbar-light bg-white py-1 fixed-top d-flex align-items-center" style="margin-top:56px;">
    <div class="navbar-text d-inline">
      <ul class="list-inline mb-0 d-flex align-items-center">
        <li class="list-inline-item text-dark">Mainchain wallet address</li>
        <li class="list-inline-item text-truncate">@(ViewBag.MainchainMultisigAddress ?? "Not running")</li>
      </ul>
    </div>
    <div class="navbar-text d-inline">
      <ul class="list-inline mb-0 ml-5 ml-md-2 d-flex align-items-center">
        <li class="list-inline-item text-dark">Apex wallet address</li>
        <li class="list-inline-item text-truncate">@(ViewBag.SidechainMultisigAddress ?? "Not Running")</li>
      </ul>
    </div>
    <div class="navbar-text ml-auto">
      <a data-toggle="modal" data-target="#miningPublicKeys" class="d-flex align-items-center"> Mining Public keys <i class="material-icons md-18 ml-2">open_in_new</i></a>
    </div>
  </nav>
  <section class="container-fluid marginTop" id="container">
    @RenderBody()
  </section>
  <script type="text/javascript" src="~/lib/signalr/dist/browser/signalr.min.js"></script>
  <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
  <script type="text/javascript" src="~/lib/popper.js/dist/umd/popper.min.js"></script>
  <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
  <script type="text/javascript" src="~/lib/node-snackbar/dist/snackbar.min.js"></script>
  <script type="text/javascript" src="~/lib/nprogress/nprogress.js"></script>
  <environment include="Development">
      <script type="text/javascript" src="~/js/default.js"></script>
  </environment>
  <environment exclude="Development">
      <script type="text/javascript" src="~/js/default.min.js"></script>
  </environment>
  @RenderSection("Scripts", false)
</body>
</html>